FROM python:3.10

ARG GRADIO_SERVER_PORT=8080
ENV GRADIO_SERVER_PORT=${GRADIO_SERVER_PORT}

WORKDIR /workspace

ADD requirements-gradio.txt app.py /workspace/

RUN pip install -r /workspace/requirements-gradio.txt

CMD ["python", "/workspace/app.py"]